name: Deploy Branch Master

on:
  push:
    branches: [master]

jobs:
  deploy:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to Heroku Container registry
        run: heroku container:login
      - name: Build and push
        run: heroku container:push -a $HEROKU_APP_NAME web
      - name: Release
        run: heroku container:release -a $HEROKU_APP_NAME web
