name: Testing

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Node.js setup
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: node clean install
        run: npm ci
      - name: start Testing
        run: npm test
